### ISSUE TITLE
Use ResizeObserver

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc-element#1]
Possible enhancement to allow all element resize events to be tracked. This [post](http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/) explains the technique.

Current workaround is to manually invoke `requestRedraw` when a resize triggering action occurs.

**Comment by chrisprice** [comment]
I have untested performance concerns about this technique.

**Comment by chrisprice** [comment]
A better technique would be to use the ResizeObserver once it is widely available 

https://developers.google.com/web/updates/2016/10/resizeobserver

**Comment by ColinEberhardt** [comment]
This issue was moved to d3fc/d3fc#1122
