### ISSUE TITLE
Suggestion - add a d3 event handler that extracts the event detail

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-element#14]
Destructuring is super-powerful, but the syntax takes quite a bit of time for me to parse!

I find this much more readable:
```
const selection = d3.event.detail.selection;
```

Than this:
```
const { detail: { selection } } = d3.event;
```

Although, when destructing to extract multiple property values I can see the advantage.

Anyhow, what about adding a way to handle custom events explicitly? Where the first argument is the `detail` property

example:
```
d3.select('#x-axis')
        .onCustom('draw', (draw) => {
            draw.selection.call(d3.axisBottom(x));
        });

d3.select('#plot-area')
    .onCustom('resize', (size) => {
        x.range([0, size.width]);
        y.range([size.height, 0]);
    })
```

**Comment by chrisprice** [comment]
Good point about destructuring, I'll change the examples. They originally
used addEventListener so they were destructing the argument. I think I just
blindly ported it over to d3 style events.

Not sure about onCustom, it breaks the datum and index pattern but I can
appreciate your frustration.

**Comment by ColinEberhardt** [comment]
True, it would break the current pattern.

Any idea why `d3.event` is a global? Scanning the D3 documentation I can't see anywhere that indicates the reason for this design decision.

**Comment by chrisprice** [comment]
No, I think it's just to keep all the arguments the same across all of the
function arguments. I know at some point there was talk of having n tuples
of (data, index) representing the nested data joins but I don't think that
ever came off.

**Comment by chrisprice** [comment]
#17 removed `selection` from the event's details. I'm happy with remaining syntax `const { width, height } = d3.event.detail`.
