### ISSUE TITLE
Package.json does not direct the build

### ISSUE THREAD

**Issue by paulhands** [d3fc/d3fc-element#22]
When trying to import requestRedraw from 'd3fc-element' I received the following error:

C:\Dev\ThreeTrader\Client\node_modules\d3fc-element\index.js:2
import 'document-register-element/build/document-register-element';
^^^^^^
SyntaxError: Unexpected token import

This error goes when importing from 'd3fc-element/build/d3fc-element'

Upon investigation it appears your package.json file does not have a "main" option to direct the build correctly

**Comment by chrisprice** [comment]
Thanks for the fix!
