### ISSUE TITLE
Throw an error if there are unexpected children of d3fc-svg/d3fc-canvas

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc-element#24]
I've just debugged a weird problem in safari which came down to the following DOM structure -

```html
<d3fc-svg>
  <svg>...</svg>
  <svg class="something">...</svg>
</d3fc-svg>
```

This is not an supported usage of the element.  There are two workarounds -

* Move the `svg.something` inside the `svg` (useful if it relates to the content of the existing `d3fc-svg`)
* Move the `svg.something` to it's own `d3fc-svg` (useful if you want to use css layout)

We should throw an error if we detect more than one child node inside the `d3fc-svg`/`d3fc-canvas` elements.

**Comment by ColinEberhardt** [comment]
see: https://github.com/d3fc/d3fc/issues/80 for context

**Comment by ColinEberhardt** [comment]
This issue was moved to d3fc/d3fc#1125
