### ISSUE TITLE
Broken module import

### ISSUE THREAD

**Issue by alisd23** [d3fc/d3fc-element#9]
There is a relative import which bypasses the node resolution system:

```js
import './node_modules/document-register-element/build/document-register-element';
```

When this project is a dependency of another project breaks this breaks, because `document-register-element` is now in the node_modules of the parent project.

**Comment by alisd23** [comment]
What was the reason for doing a relative import here?

**Comment by chrisprice** [comment]
When I added that there wasn't node resolution in the bundling. Any chance
you could add a fix please?

**Comment by alisd23** [comment]
Just noticed master looks correct, so the fixed version just hasn't been published

**Comment by alisd23** [comment]
So the [9342124](https://github.com/d3fc/d3fc-element/commit/9342124) commit didn't release. Maybe `refactor` isn't a valid semver release keyword?

**Comment by chrisprice** [comment]
I think you're right. Can you stick a docs change or similar in with a fix
commit message to trigger the release?

**Comment by alisd23** [comment]
https://github.com/d3fc/d3fc-element/pull/10
I can't merge PR's yet

**Comment by chrisprice** [comment]
It needs to be a fix: x, docs won't trigger it.

**Comment by alisd23** [comment]
#11 is now a fix commit, the import actually needed fixing anyway
